[2025-01-17T22:21:18.359+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T22:21:18.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_articles manual__2025-01-17T22:14:24.591389+00:00 [queued]>
[2025-01-17T22:21:18.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_articles manual__2025-01-17T22:14:24.591389+00:00 [queued]>
[2025-01-17T22:21:18.393+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-01-17T22:21:18.409+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_articles> on 2025-01-17 22:14:24.591389+00:00
[2025-01-17T22:21:18.420+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=544) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T22:21:18.421+0000] {standard_task_runner.py:72} INFO - Started process 546 to run task
[2025-01-17T22:21:18.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spaceflight_data_ingest_v2', 'fetch_articles', 'manual__2025-01-17T22:14:24.591389+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/spaceflight_data_ingest_v2.py', '--cfg-path', '/tmp/tmp6tmtsr41']
[2025-01-17T22:21:18.423+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask fetch_articles
[2025-01-17T22:21:18.480+0000] {task_command.py:467} INFO - Running <TaskInstance: spaceflight_data_ingest_v2.fetch_articles manual__2025-01-17T22:14:24.591389+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T22:21:18.808+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spaceflight_data_ingest_v2' AIRFLOW_CTX_TASK_ID='fetch_articles' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T22:14:24.591389+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T22:14:24.591389+00:00'
[2025-01-17T22:21:18.808+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T22:21:18.808+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T22:21:18.809+0000] {logging_mixin.py:190} INFO - Current task name:fetch_articles state:running start_date:2025-01-17 22:21:18.381495+00:00
[2025-01-17T22:21:18.809+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 and current dag run status:running
[2025-01-17T22:21:18.809+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T22:21:19.419+0000] {spaceflight_data_ingest_v2.py:80} ERROR - Error en la solicitud: 'id'
[2025-01-17T22:21:19.419+0000] {spaceflight_data_ingest_v2.py:84} INFO - Reintentando... intento 1/5
[2025-01-17T22:21:21.776+0000] {spaceflight_data_ingest_v2.py:84} INFO - Reintentando... intento 2/5
[2025-01-17T22:21:26.778+0000] {spaceflight_data_ingest_v2.py:84} INFO - Reintentando... intento 3/5
[2025-01-17T22:21:31.779+0000] {spaceflight_data_ingest_v2.py:84} INFO - Reintentando... intento 4/5
[2025-01-17T22:21:36.782+0000] {spaceflight_data_ingest_v2.py:84} INFO - Reintentando... intento 5/5
[2025-01-17T22:21:41.784+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-17T22:21:41.797+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T22:21:41.797+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=spaceflight_data_ingest_v2, task_id=fetch_articles, run_id=manual__2025-01-17T22:14:24.591389+00:00, execution_date=20250117T221424, start_date=20250117T222118, end_date=20250117T222141
[2025-01-17T22:21:41.812+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-17T22:21:41.813+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-17T22:21:41.813+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 queued_at:2025-01-17 22:14:24.604201+00:00
[2025-01-17T22:21:41.813+0000] {logging_mixin.py:190} INFO - Task hostname:59ff16f1d4fb operator:PythonOperator
[2025-01-17T22:21:41.849+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T22:21:42.099+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-17T22:21:42.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
