[2025-01-21T01:01:33.268+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T01:01:33.290+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-21T00:59:16.128748+00:00 [queued]>
[2025-01-21T01:01:33.304+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-21T00:59:16.128748+00:00 [queued]>
[2025-01-21T01:01:33.305+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-21T01:01:33.326+0000] {taskinstance.py:2889} INFO - Executing <Task(GlueJobOperator): glue_sparkJob> on 2025-01-21 00:59:16.128748+00:00
[2025-01-21T01:01:33.338+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3952) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T01:01:33.340+0000] {standard_task_runner.py:72} INFO - Started process 3954 to run task
[2025-01-21T01:01:33.340+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_AWS_PIPELINE', 'glue_sparkJob', 'manual__2025-01-21T00:59:16.128748+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/Ingesta_aws.py', '--cfg-path', '/tmp/tmp5yz_uh0t']
[2025-01-21T01:01:33.341+0000] {standard_task_runner.py:105} INFO - Job 336: Subtask glue_sparkJob
[2025-01-21T01:01:33.411+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-21T00:59:16.128748+00:00 [running]> on host 59ff16f1d4fb
[2025-01-21T01:01:33.506+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Wilfrido Rondon' AIRFLOW_CTX_DAG_ID='DAG_AWS_PIPELINE' AIRFLOW_CTX_TASK_ID='glue_sparkJob' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:59:16.128748+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T00:59:16.128748+00:00'
[2025-01-21T01:01:33.507+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-21T01:01:33.507+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-21T01:01:33.508+0000] {logging_mixin.py:190} INFO - Current task name:glue_sparkJob state:running start_date:2025-01-21 01:01:33.290538+00:00
[2025-01-21T01:01:33.508+0000] {logging_mixin.py:190} INFO - Dag name:DAG_AWS_PIPELINE and current dag run status:running
[2025-01-21T01:01:33.508+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T01:01:33.508+0000] {glue.py:195} INFO - Initializing AWS Glue Job: JoSpaceFligthV2. Wait for completion: True
[2025-01-21T01:01:33.509+0000] {glue.py:369} INFO - Checking if job already exists: JoSpaceFligthV2
[2025-01-21T01:01:33.519+0000] {base.py:84} INFO - Retrieving connection 'aws_conn'
[2025-01-21T01:01:33.519+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2025-01-21T01:01:34.420+0000] {glue.py:191} ERROR - Failed to run aws glue job, error: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded.
[2025-01-21T01:01:34.421+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 200, in execute
    glue_job_run = self.glue_job_hook.initialize_job(self.script_args, self.run_job_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 189, in initialize_job
    return self.conn.start_job_run(JobName=job_name, Arguments=script_arguments, **run_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConcurrentRunsExceededException: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded.
[2025-01-21T01:01:34.431+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-21T01:01:34.431+0000] {logging_mixin.py:190} INFO - Task start:2025-01-21 01:01:33.290538+00:00 end:2025-01-21 01:01:34.430642+00:00 duration:1.140104
[2025-01-21T01:01:34.431+0000] {logging_mixin.py:190} INFO - Task:<Task(GlueJobOperator): glue_sparkJob> dag:<DAG: DAG_AWS_PIPELINE> dagrun:<DagRun DAG_AWS_PIPELINE @ 2025-01-21 00:59:16.128748+00:00: manual__2025-01-21T00:59:16.128748+00:00, state:running, queued_at: 2025-01-21 00:59:16.140064+00:00. externally triggered: True>
[2025-01-21T01:01:34.432+0000] {logging_mixin.py:190} INFO - Failure caused by An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded.
[2025-01-21T01:01:34.432+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=DAG_AWS_PIPELINE, task_id=glue_sparkJob, run_id=manual__2025-01-21T00:59:16.128748+00:00, execution_date=20250121T005916, start_date=20250121T010133, end_date=20250121T010134
[2025-01-21T01:01:34.445+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-21T01:01:34.445+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 336 for task glue_sparkJob (An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded.; 3954)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 200, in execute
    glue_job_run = self.glue_job_hook.initialize_job(self.script_args, self.run_job_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 189, in initialize_job
    return self.conn.start_job_run(JobName=job_name, Arguments=script_arguments, **run_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConcurrentRunsExceededException: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded.
[2025-01-21T01:01:34.487+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-21T01:01:34.510+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-21T01:01:34.518+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
