[2025-01-17T22:11:28.057+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T22:11:28.077+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:11:25.781976+00:00 [queued]>
[2025-01-17T22:11:28.087+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:11:25.781976+00:00 [queued]>
[2025-01-17T22:11:28.088+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T22:11:28.106+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2025-01-17 22:11:25.781976+00:00
[2025-01-17T22:11:28.117+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T22:11:28.119+0000] {standard_task_runner.py:72} INFO - Started process 392 to run task
[2025-01-17T22:11:28.119+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_to_csv_dag', 'fetch_and_save_data', 'manual__2025-01-17T22:11:25.781976+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/prueba_api.py', '--cfg-path', '/tmp/tmp4fksdg_i']
[2025-01-17T22:11:28.121+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask fetch_and_save_data
[2025-01-17T22:11:28.182+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:11:25.781976+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T22:11:28.504+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_csv_dag' AIRFLOW_CTX_TASK_ID='fetch_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T22:11:25.781976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T22:11:25.781976+00:00'
[2025-01-17T22:11:28.505+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T22:11:28.506+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T22:11:28.506+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_save_data state:running start_date:2025-01-17 22:11:28.078450+00:00
[2025-01-17T22:11:28.506+0000] {logging_mixin.py:190} INFO - Dag name:api_to_csv_dag and current dag run status:running
[2025-01-17T22:11:28.506+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T22:11:29.021+0000] {prueba_api.py:38} WARNING - No se encontraron datos en la respuesta de la API.
[2025-01-17T22:11:29.022+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-17T22:11:29.032+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T22:11:29.033+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_to_csv_dag, task_id=fetch_and_save_data, run_id=manual__2025-01-17T22:11:25.781976+00:00, execution_date=20250117T221125, start_date=20250117T221128, end_date=20250117T221129
[2025-01-17T22:11:29.048+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-17T22:11:29.048+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-17T22:11:29.049+0000] {logging_mixin.py:190} INFO - Dag name:api_to_csv_dag queued_at:2025-01-17 22:11:25.799670+00:00
[2025-01-17T22:11:29.049+0000] {logging_mixin.py:190} INFO - Task hostname:59ff16f1d4fb operator:PythonOperator
[2025-01-17T22:11:29.076+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T22:11:29.094+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T22:11:29.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
