[2025-01-17T22:12:12.964+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T22:12:12.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:12:10.818433+00:00 [queued]>
[2025-01-17T22:12:12.995+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:12:10.818433+00:00 [queued]>
[2025-01-17T22:12:12.995+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T22:12:13.012+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_save_data> on 2025-01-17 22:12:10.818433+00:00
[2025-01-17T22:12:13.022+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=401) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T22:12:13.024+0000] {standard_task_runner.py:72} INFO - Started process 403 to run task
[2025-01-17T22:12:13.025+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'api_to_csv_dag', 'fetch_and_save_data', 'manual__2025-01-17T22:12:10.818433+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/prueba_api.py', '--cfg-path', '/tmp/tmpee30ki77']
[2025-01-17T22:12:13.026+0000] {standard_task_runner.py:105} INFO - Job 96: Subtask fetch_and_save_data
[2025-01-17T22:12:13.328+0000] {task_command.py:467} INFO - Running <TaskInstance: api_to_csv_dag.fetch_and_save_data manual__2025-01-17T22:12:10.818433+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T22:12:13.419+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_csv_dag' AIRFLOW_CTX_TASK_ID='fetch_and_save_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T22:12:10.818433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T22:12:10.818433+00:00'
[2025-01-17T22:12:13.420+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T22:12:13.420+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T22:12:13.420+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_save_data state:running start_date:2025-01-17 22:12:12.985214+00:00
[2025-01-17T22:12:13.421+0000] {logging_mixin.py:190} INFO - Dag name:api_to_csv_dag and current dag run status:running
[2025-01-17T22:12:13.421+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T22:12:13.791+0000] {prueba_api.py:38} WARNING - No se encontraron datos en la respuesta de la API.
[2025-01-17T22:12:13.791+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-17T22:12:13.804+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T22:12:13.805+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=api_to_csv_dag, task_id=fetch_and_save_data, run_id=manual__2025-01-17T22:12:10.818433+00:00, execution_date=20250117T221210, start_date=20250117T221212, end_date=20250117T221213
[2025-01-17T22:12:13.821+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-17T22:12:13.822+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-17T22:12:13.822+0000] {logging_mixin.py:190} INFO - Dag name:api_to_csv_dag queued_at:2025-01-17 22:12:10.838721+00:00
[2025-01-17T22:12:13.822+0000] {logging_mixin.py:190} INFO - Task hostname:59ff16f1d4fb operator:PythonOperator
[2025-01-17T22:12:13.890+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T22:12:11.544+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T22:12:11.546+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
